using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Oathsunder.Combat.Content;
using Oathsunder.Combat.Definitions;
using Oathsunder.Core.Mathematics;
using Oathsunder.Presentation.Animation;
using Oathsunder.Presentation.Cues;

namespace Oathsunder.Tools
{
    /// <summary>One animation production sheet per move (Documentation/Production/03-Animation/Generated-AnimationLibrary.md).</summary>
    internal static class AnimationLibraryReport
    {
        public static string Build(CombatContentSet content, List<(string Weapon, FighterBlueprint Blueprint, List<MoveAnimationSpec> Specs)> fighters, CueCatalog catalog)
        {
            var text = new StringBuilder();
            text.AppendLine("<!-- Generated by Tools/DotNet/Oathsunder.Tools.FrameData from the running simulation. Do not edit by hand. -->");
            text.AppendLine();
            text.AppendLine("# Animation library — production sheets");
            text.AppendLine();
            text.AppendLine("Every sheet below is **captured from the deterministic simulation** (`MoveAnimationCapture`), not typed by hand: when");
            text.AppendLine("move data changes, CI fails until this file is regenerated, so the animation contract and gameplay cannot drift.");
            text.AppendLine("Authoring rules, the rig and the review process are in [00-AnimationStandards.md](00-AnimationStandards.md).");
            text.AppendLine();
            text.AppendLine("**How to read a sheet**");
            text.AppendLine();
            text.AppendLine("- Frames are 1-based at 60 fps. The clip has exactly *Frames* frames; clip time *t* = (frame − 1) / 60 s.");
            text.AppendLine("- *Timeline* has one character per frame. `phase`: S startup, A active, g gap between hits, R recovery, `-` non-attack.");
            text.AppendLine("  `hitbox`: hit group number while a hitbox is live. `hurt`: s standing, c crouching, a airborne stance boxes,");
            text.AppendLine("  **upper case** when the move extends or replaces them. `defence`: I fully invulnerable, s/t/p strike/throw/projectile");
            text.AppendLine("  invulnerable, E perfect-evade window, K counter stance, A armor. `cancel`: c when a cancel window is open.");
            text.AppendLine("  Trigger lanes mark cue frames (`*` = several on one frame).");
            text.AppendLine("- *Root X/Y* is the captured root offset in metres at the end of each frame, run-length encoded (`0.10×5` = five");
            text.AppendLine("  frames at 0.10). Clips are authored **in place**; match foot contacts to this curve.");
            text.AppendLine("- *On contact* cues are fired by the simulation on the frame a hit lands (hitstop freezes the Contact pose).");
            text.AppendLine();

            foreach (var (weapon, blueprint, specs) in fighters)
            {
                text.AppendLine($"## {content.MoveSet(weapon).DisplayName} (`{weapon}`) + universal techniques — `{blueprint.Body.Id}`");
                text.AppendLine();
                text.AppendLine("| Clip | Move | Frames | S / A / R | Root motion | Travel X (m) |");
                text.AppendLine("|---|---|---:|---|---|---:|");
                var headings = Headings(specs);
                foreach (var spec in specs)
                {
                    text.AppendLine($"| [`{spec.Clip}`](#{Anchor(headings[spec])}) | {spec.Move.Id} | {spec.Move.TotalFrames} | {Sar(spec)} | {spec.RootMotion} | {spec.FinalOffset.X.ToDouble().ToString("0.00", CultureInfo.InvariantCulture)} |");
                }

                text.AppendLine();
                StateClips(text, content, blueprint);
                foreach (var spec in specs)
                {
                    Sheet(text, blueprint, spec, headings[spec], catalog);
                }
            }

            return text.ToString();
        }

        /// <summary>The non-move clip library (locomotion, defence, reactions, knockdowns) with its timing drivers.</summary>
        private static void StateClips(StringBuilder text, CombatContentSet content, FighterBlueprint blueprint)
        {
            var rules = content.Rules("rules.story");
            text.AppendLine($"### Fighter state clips — `{blueprint.Body.Id}`");
            text.AppendLine();
            text.AppendLine("Played by `FighterPoseSampler` for every non-move state. *Loop* clips repeat; *FixedDuration* clips play once over the");
            text.AppendLine("listed frames (from the fighter data); *StunDuration* clips are authored at the reference length and time-warped to");
            text.AppendLine("the stun each hit applies; *VerticalVelocity* clips are sampled by vertical speed (take-off → apex → fall);");
            text.AppendLine($"knock-out uses the story rules' hold ({rules.KnockoutHoldFrames} frames).");
            text.AppendLine();
            text.AppendLine("| Clip | Played in | Driver | Frames | Must show |");
            text.AppendLine("|---|---|---|---:|---|");
            foreach (var clip in FighterPoseSampler.StateClips(blueprint.Body, content.Tuning, rules))
            {
                text.AppendLine($"| `{clip.Clip}` | {clip.Actions} | {clip.Driver} | {clip.Frames} | {clip.Content} |");
            }

            text.AppendLine();
        }

        /// <summary>Sheet headings: the clip name, plus the move id when several moves share a clip.</summary>
        private static Dictionary<MoveAnimationSpec, string> Headings(List<MoveAnimationSpec> specs)
        {
            var shared = specs.GroupBy(s => s.Clip).Where(g => g.Count() > 1).Select(g => g.Key).ToHashSet(StringComparer.Ordinal);
            return specs.ToDictionary(s => s, s => shared.Contains(s.Clip) ? $"{s.Clip} ({s.Move.Id})" : s.Clip);
        }

        private static void Sheet(StringBuilder text, FighterBlueprint blueprint, MoveAnimationSpec spec, string heading, CueCatalog catalog)
        {
            var move = spec.Move;
            text.AppendLine($"### {heading}");
            text.AppendLine();
            text.AppendLine($"**{move.Name}** — `{move.Id}` · tags {move.Tags}{(move.Flags != 0 ? " · flags " + move.Flags : "")}");
            text.AppendLine();
            text.AppendLine("| Frames | Seconds | Startup | Active | Recovery | Root motion | Travel (x, y) m | Hitstop |");
            text.AppendLine("|---:|---:|---:|---|---:|---|---|---|");
            string active = move.IsAttack ? $"{move.FirstActiveFrame}–{move.LastActiveFrame} ({spec.ActiveSpan})" : "—";
            string hitstop = spec.Contacts.Count == 0 ? "—" : string.Join(", ", spec.Contacts.Select(c => c.Hitstop.ToString(CultureInfo.InvariantCulture)));
            text.AppendLine(string.Format(CultureInfo.InvariantCulture, "| {0} | {1:0.000} | {2} | {3} | {4} | {5} | {6}, {7} | {8} |",
                move.TotalFrames, spec.Seconds, move.IsAttack ? spec.Startup.ToString(CultureInfo.InvariantCulture) : "—", active,
                move.IsAttack ? spec.Recovery.ToString(CultureInfo.InvariantCulture) : "—", spec.RootMotion,
                AnimationSpecJson.Metres(spec.FinalOffset.X), AnimationSpecJson.Metres(spec.FinalOffset.Y), hitstop));
            text.AppendLine();

            text.AppendLine("```text");
            foreach (var line in Timeline(blueprint, spec))
            {
                text.AppendLine(line);
            }

            text.AppendLine("```");
            text.AppendLine();

            text.AppendLine("| Key frame | Pose | Must show |");
            text.AppendLine("|---:|---|---|");
            foreach (var pose in spec.KeyPoses)
            {
                text.AppendLine($"| {pose.Frame} | {pose.Name} | {pose.Purpose} |");
            }

            text.AppendLine();
            if (spec.Root.Length > 0)
            {
                text.AppendLine($"Root X (m): {RunLength(spec.Root.Select(r => r.Offset.X))}");
                if (spec.Root.Any(r => r.Offset.Y != Fixed.Zero))
                {
                    text.AppendLine();
                    text.AppendLine($"Root Y (m): {RunLength(spec.Root.Select(r => r.Offset.Y))}");
                }

                text.AppendLine();
            }

            if (move.Hitboxes.Length > 0)
            {
                text.AppendLine("| Hitbox frames | Group | Attack | Box x, y, w, h (m, facing right) |");
                text.AppendLine("|---|---:|---|---|");
                foreach (var hitbox in move.Hitboxes)
                {
                    text.AppendLine($"| {hitbox.Window.Start}–{hitbox.Window.End} | {hitbox.Group + 1} | {move.Attacks[hitbox.AttackIndex].Key} | {Box(hitbox.Box)} |");
                }

                text.AppendLine();
            }

            text.AppendLine("| Hurt frames | Stance | Hurtboxes x, y, w, h (m) | Defence |");
            text.AppendLine("|---|---|---|---|");
            foreach (var range in AnimationSpecJson.HurtRanges(spec))
            {
                var state = range.State;
                var defence = new List<string>();
                if (state.Invulnerable != InvulnerabilityMask.None)
                {
                    defence.Add("invulnerable: " + state.Invulnerable);
                }

                if (state.PerfectEvade)
                {
                    defence.Add("perfect evade");
                }

                if (state.CounterStance)
                {
                    defence.Add("counter stance");
                }

                if (state.Armor)
                {
                    defence.Add("armor");
                }

                text.AppendLine($"| {range.Start}–{range.End} | {state.Stance} | {string.Join("; ", state.Boxes.Select(Box))} | {(defence.Count == 0 ? "—" : string.Join(", ", defence))} |");
            }

            text.AppendLine();
            text.AppendLine("| Trigger frame | Channel | Cue | Asset | Production note |");
            text.AppendLine("|---:|---|---|---|---|");
            foreach (var cue in spec.Cues)
            {
                catalog.TryGet(cue.Name, out var def);
                text.AppendLine($"| {cue.Frame} | {CueNames.Prefix(cue.Channel)} | `{cue.Name}` | {(def == null || def.Asset.Length == 0 ? "—" : "`" + def.Asset + "`")} | {def?.Description ?? "missing from catalog"} |");
            }

            text.AppendLine();
            if (spec.Contacts.Count > 0)
            {
                text.AppendLine("| On contact (group, frames) | Hit | Counter hit | Blocked | Layers played on hit |");
                text.AppendLine("|---|---|---|---|---|");
                var layers = new List<CueDefinition>();
                foreach (var contact in spec.Contacts)
                {
                    layers.Clear();
                    catalog.Expand(contact.OnHit, layers);
                    text.AppendLine($"| {contact.Group + 1}, {contact.Window.Start}–{contact.Window.End} | `{contact.OnHit}` | {Code(contact.OnCounterHit)} | {Code(contact.OnBlock)} | {string.Join(", ", layers.Select(l => l.Name))} |");
                }

                text.AppendLine();
            }

            if (spec.Notes.Count > 0)
            {
                foreach (var note in spec.Notes)
                {
                    text.AppendLine($"- {note}");
                }

                text.AppendLine();
            }
        }

        private static IEnumerable<string> Timeline(FighterBlueprint blueprint, MoveAnimationSpec spec)
        {
            var move = spec.Move;
            int n = move.TotalFrames;
            var ruler = new char[n];
            for (int i = 0; i < n; i++)
            {
                ruler[i] = ' ';
            }

            for (int frame = 1; frame <= n; frame++)
            {
                if (frame == 1 || frame % 5 == 0)
                {
                    string label = frame.ToString(CultureInfo.InvariantCulture);
                    if (frame - 1 + label.Length <= n && (frame == 1 || ruler[frame - 2] == ' '))
                    {
                        for (int c = 0; c < label.Length; c++)
                        {
                            ruler[frame - 1 + c] = label[c];
                        }
                    }
                }
            }

            yield return "frame      " + new string(ruler);
            yield return "phase      " + Lane(n, f => spec.Phases[f - 1] switch
            {
                MovePhase.Startup => 'S',
                MovePhase.Active => 'A',
                MovePhase.Gap => 'g',
                MovePhase.Recovery => 'R',
                _ => '-',
            });
            if (move.Hitboxes.Length > 0)
            {
                yield return "hitbox     " + Lane(n, f =>
                {
                    foreach (var hitbox in move.Hitboxes)
                    {
                        if (hitbox.Window.Contains(f))
                        {
                            return (char)('1' + hitbox.Group);
                        }
                    }

                    return '.';
                });
            }

            var hurtByFrame = spec.Hurt.ToDictionary(h => h.Frame);
            yield return "hurt       " + Lane(n, f =>
            {
                if (!hurtByFrame.TryGetValue(f, out var state))
                {
                    return ' ';
                }

                char stance = state.Stance.Length > 0 ? state.Stance[0] : '?';
                return IsPlainStance(blueprint, state) ? stance : char.ToUpperInvariant(stance);
            });
            yield return "defence    " + Lane(n, f =>
            {
                if (!hurtByFrame.TryGetValue(f, out var state))
                {
                    return ' ';
                }

                if (state.Invulnerable == InvulnerabilityMask.All)
                {
                    return 'I';
                }

                if (state.CounterStance)
                {
                    return 'K';
                }

                if (state.PerfectEvade)
                {
                    return 'E';
                }

                if (state.Armor)
                {
                    return 'A';
                }

                if ((state.Invulnerable & InvulnerabilityMask.Strike) != 0)
                {
                    return 's';
                }

                if ((state.Invulnerable & InvulnerabilityMask.Throw) != 0)
                {
                    return 't';
                }

                return (state.Invulnerable & InvulnerabilityMask.Projectile) != 0 ? 'p' : '.';
            });
            if (move.Cancels.Length > 0)
            {
                yield return "cancel     " + Lane(n, f => move.Cancels.Any(c => c.Window.Contains(f)) ? 'c' : '.');
            }

            yield return "sfx/foley  " + CueLane(spec, n, 's', CueChannel.Sfx, CueChannel.Foley);
            yield return "vfx        " + CueLane(spec, n, 'v', CueChannel.Vfx);
            yield return "voice      " + CueLane(spec, n, 'o', CueChannel.Vo);
            yield return "camera     " + CueLane(spec, n, 'c', CueChannel.Cam);
            if (spec.Cues.Any(c => c.Channel == CueChannel.Haptic))
            {
                yield return "haptic     " + CueLane(spec, n, 'h', CueChannel.Haptic);
            }

            if (spec.Contacts.Count > 0 || spec.ProjectileFrames.Count > 0 || move.Paired != null)
            {
                yield return "contact    " + Lane(n, f =>
                {
                    if (spec.ProjectileFrames.Contains(f))
                    {
                        return 'P';
                    }

                    if (move.Paired != null)
                    {
                        if (move.Paired.Hits.Any(h => h.Frame == f))
                        {
                            return 'x';
                        }

                        return move.Paired.ReleaseFrame == f ? 'r' : '.';
                    }

                    return spec.Contacts.Any(c => c.Window.Contains(f)) ? 'x' : '.';
                });
            }
        }

        private static bool IsPlainStance(FighterBlueprint blueprint, HurtState state)
        {
            var body = blueprint.Body;
            var stance = state.Stance == "crouching" ? body.Crouching : state.Stance == "airborne" ? body.Airborne : body.Standing;
            if (stance.Hurtboxes.Length != state.Boxes.Length)
            {
                return false;
            }

            for (int i = 0; i < state.Boxes.Length; i++)
            {
                if (!stance.Hurtboxes[i].Equals(state.Boxes[i]))
                {
                    return false;
                }
            }

            return true;
        }

        private static string CueLane(MoveAnimationSpec spec, int n, char mark, params CueChannel[] channels) =>
            Lane(n, f =>
            {
                int count = spec.Cues.Count(c => c.Frame == f && channels.Contains(c.Channel));
                return count == 0 ? '.' : count == 1 ? mark : '*';
            });

        private static string Lane(int n, Func<int, char> at)
        {
            var chars = new char[n];
            for (int f = 1; f <= n; f++)
            {
                chars[f - 1] = at(f);
            }

            return new string(chars);
        }

        private static string RunLength(IEnumerable<Fixed> values)
        {
            var parts = new List<string>();
            string previous = null;
            int count = 0;
            foreach (var value in values)
            {
                string text = value.ToDouble().ToString("0.00", CultureInfo.InvariantCulture);
                if (text == previous)
                {
                    count++;
                    continue;
                }

                if (previous != null)
                {
                    parts.Add(count > 1 ? $"{previous}×{count}" : previous);
                }

                previous = text;
                count = 1;
            }

            if (previous != null)
            {
                parts.Add(count > 1 ? $"{previous}×{count}" : previous);
            }

            return string.Join(" ", parts);
        }

        private static string Sar(MoveAnimationSpec spec) =>
            spec.Move.IsAttack ? $"{spec.Startup} / {spec.ActiveSpan} / {spec.Recovery}" : "—";

        private static string Box(FixedAabb box) => string.Format(CultureInfo.InvariantCulture, "{0:0.00}, {1:0.00}, {2:0.00}, {3:0.00}",
            box.Min.X.ToDouble(), box.Min.Y.ToDouble(), box.Width.ToDouble(), box.Height.ToDouble());

        private static string Code(string cue) => string.IsNullOrEmpty(cue) ? "—" : $"`{cue}`";

        /// <summary>GitHub heading anchor: lower case, punctuation other than '-' and '_' removed, spaces to '-'.</summary>
        private static string Anchor(string heading)
        {
            var anchor = new StringBuilder(heading.Length);
            foreach (char c in heading.ToLowerInvariant())
            {
                if (char.IsLetterOrDigit(c) || c == '_' || c == '-')
                {
                    anchor.Append(c);
                }
                else if (c == ' ')
                {
                    anchor.Append('-');
                }
            }

            return anchor.ToString();
        }
    }
}
