using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Oathsunder.Combat.Definitions;
using Oathsunder.Combat.Events;
using Oathsunder.Core.Mathematics;
using Oathsunder.Presentation.Cues;

namespace Oathsunder.Tools
{
    /// <summary>The production list of every presentation cue (Documentation/Production/Generated-CueCatalog.md).</summary>
    internal static class CueCatalogReport
    {
        /// <summary>Weapon classes that need a {Weapon} family (canon §6).</summary>
        private const int WeaponClasses = 13;

        /// <summary>Voiced combatants that need a {Character} bank: 8 principal characters + 24 bosses.</summary>
        private const int VoicedCombatants = 32;

        public static string Build(CueCatalog catalog, List<FighterBlueprint> blueprints)
        {
            var usedBy = UsedBy(catalog, blueprints);
            var text = new StringBuilder();
            text.AppendLine("<!-- Generated by Tools/DotNet/Oathsunder.Tools.FrameData from Content/Presentation/cues.combat.json. Do not edit by hand. -->");
            text.AppendLine();
            text.AppendLine("# Cue catalog — production list");
            text.AppendLine();
            text.AppendLine($"`{catalog.Id}` declares **{catalog.Count} cues**. Each row is a deliverable with its technical specification;");
            text.AppendLine("the catalog JSON is validated in CI (grammar, variation minimums, particle budgets, photosensitivity caps, asset prefixes)");
            text.AppendLine("and every move must pass the presentation Definition of Done (`CueCoverage`). Editing guide:");
            text.AppendLine("[03-Animation/00-AnimationStandards.md](03-Animation/00-AnimationStandards.md), [04-VFX/00-VfxStandards.md](04-VFX/00-VfxStandards.md),");
            text.AppendLine("[06-Audio/README.md](06-Audio/README.md).");
            text.AppendLine();
            text.AppendLine("| Channel | Cues | Files to produce |");
            text.AppendLine("|---|---:|---|");
            foreach (CueChannel channel in Enum.GetValues(typeof(CueChannel)))
            {
                var cues = catalog.OfChannel(channel).ToList();
                text.AppendLine($"| {CueNames.Prefix(channel)} | {cues.Count} | {Files(channel, cues)} |");
            }

            text.AppendLine();
            text.AppendLine("`{Weapon}` assets are produced once per weapon class (13); `{Character}` assets once per voiced combatant (8 principal");
            text.AppendLine("characters + 24 bosses). Blood layers (`gore`) are skipped when the player disables blood.");

            text.AppendLine();
            text.AppendLine("## VFX");
            text.AppendLine();
            text.AppendLine("Particle budgets are maximum live particles per tier: mobile low / mobile mid / mobile high / PC. Distortion runs on mobile high");
            text.AppendLine("and PC only; realtime lights on PC only.");
            text.AppendLine();
            text.AppendLine("| Cue | Asset | Attach | Life (f) | Particles | Flags | Must show | Fired by |");
            text.AppendLine("|---|---|---|---:|---|---|---|---|");
            foreach (var cue in catalog.OfChannel(CueChannel.Vfx))
            {
                var v = cue.Vfx;
                var flags = new List<string>();
                if (v.Distortion)
                {
                    flags.Add("distortion");
                }

                if (v.Light)
                {
                    flags.Add("light");
                }

                if (v.Gore)
                {
                    flags.Add("gore");
                }

                text.AppendLine($"| `{cue.Name}` | `{cue.Asset}` | {v.Attach} | {v.LifetimeFrames} | {string.Join(" / ", v.Particles)} | {(flags.Count == 0 ? "—" : string.Join(", ", flags))} | {cue.Description} | {usedBy[cue.Name]} |");
            }

            foreach (var (title, channel) in new[] { ("Sound effects", CueChannel.Sfx), ("Foley", CueChannel.Foley), ("Voice", CueChannel.Vo) })
            {
                text.AppendLine();
                text.AppendLine($"## {title}");
                text.AppendLine();
                text.AppendLine("| Cue | Asset | Var. | Bus | Gain dB | Pitch ± cents | Chance | Must sound like | Fired by |");
                text.AppendLine("|---|---|---:|---|---:|---:|---:|---|---|");
                foreach (var cue in catalog.OfChannel(channel))
                {
                    var a = cue.Audio;
                    text.AppendLine(string.Format(CultureInfo.InvariantCulture, "| `{0}` | `{1}` | {2} | {3} | {4:0.#} | {5} | {6}% | {7} | {8} |",
                        cue.Name, cue.Asset, a.Variations, a.Bus, a.VolumeDb, a.PitchJitterCents, a.ChancePercent, cue.Description, usedBy[cue.Name]));
                }
            }

            text.AppendLine();
            text.AppendLine("## Camera");
            text.AppendLine();
            text.AppendLine("Amplitude units: shake metres, push fraction of camera distance, tilt and zoom degrees, flash peak opacity. All camera");
            text.AppendLine("motion is scaled by the player's camera-motion setting; flashes can be disabled (photosensitivity).");
            text.AppendLine();
            text.AppendLine("| Cue | Kind | Amplitude | Frequency Hz | Frames | Extra | Intent | Fired by |");
            text.AppendLine("|---|---|---:|---:|---:|---|---|---|");
            foreach (var cue in catalog.OfChannel(CueChannel.Cam))
            {
                var c = cue.Camera;
                string extra = c.Kind == CameraCueKind.SlowMotion ? $"time scale {c.TimeScale.ToString("0.##", CultureInfo.InvariantCulture)}"
                    : c.Kind == CameraCueKind.Sequence ? $"`{c.Sequence}`" : "—";
                text.AppendLine(string.Format(CultureInfo.InvariantCulture, "| `{0}` | {1} | {2} | {3} | {4} | {5} | {6} | {7} |",
                    cue.Name, c.Kind, c.Amplitude == 0f ? "—" : c.Amplitude.ToString("0.###", CultureInfo.InvariantCulture),
                    c.Frequency == 0f ? "—" : c.Frequency.ToString("0.#", CultureInfo.InvariantCulture), c.Frames, extra, cue.Description, usedBy[cue.Name]));
            }

            text.AppendLine();
            text.AppendLine("## Haptics");
            text.AppendLine();
            text.AppendLine("| Cue | Amplitude | Duration ms | Intent | Fired by |");
            text.AppendLine("|---|---:|---:|---|---|");
            foreach (var cue in catalog.OfChannel(CueChannel.Haptic))
            {
                text.AppendLine(string.Format(CultureInfo.InvariantCulture, "| `{0}` | {1:0.##} | {2} | {3} | {4} |",
                    cue.Name, cue.Haptic.Amplitude, cue.Haptic.DurationMs, cue.Description, usedBy[cue.Name]));
            }

            text.AppendLine();
            text.AppendLine("## Impact composites (event-driven)");
            text.AppendLine();
            text.AppendLine("Fired by the simulation's combat events through `EventCueMap`; move data may not fire them. Voice layers named `vo.hurt.*`");
            text.AppendLine("speak as the victim.");
            text.AppendLine();
            text.AppendLine("| Cue | Combat event | Layers | Intent |");
            text.AppendLine("|---|---|---|---|");
            var events = EventSources();
            foreach (var cue in catalog.OfChannel(CueChannel.Impact))
            {
                text.AppendLine($"| `{cue.Name}` | {(events.TryGetValue(cue.Name, out var source) ? source : "—")} | {string.Join(", ", cue.Layers.Select(l => $"`{l}`"))} | {cue.Description} |");
            }

            return text.ToString();
        }

        private static string Files(CueChannel channel, List<CueDefinition> cues)
        {
            switch (channel)
            {
                case CueChannel.Vfx:
                    return $"{cues.Count} prefabs (+ optional mobile-low variants)";
                case CueChannel.Sfx:
                case CueChannel.Foley:
                case CueChannel.Vo:
                    int files = 0;
                    foreach (var cue in cues)
                    {
                        int multiplier = cue.Asset.Contains("{Weapon}") ? WeaponClasses : cue.Asset.Contains("{Character}") ? VoicedCombatants : 1;
                        files += cue.Audio.Variations * multiplier;
                    }

                    return $"{files} audio files";
                case CueChannel.Cam:
                    int sequences = cues.Count(c => c.Camera.Kind == CameraCueKind.Sequence);
                    return $"{sequences} Timeline sequences; the rest are parameters";
                default:
                    return "parameters only";
            }
        }

        private static Dictionary<string, string> UsedBy(CueCatalog catalog, List<FighterBlueprint> blueprints)
        {
            var users = catalog.Cues.ToDictionary(c => c.Name, _ => new SortedSet<string>(StringComparer.Ordinal), StringComparer.Ordinal);
            foreach (var blueprint in blueprints)
            {
                foreach (var move in blueprint.Moves)
                {
                    foreach (var cue in move.Cues)
                    {
                        if (users.TryGetValue(cue.Name, out var set))
                        {
                            set.Add(move.Id);
                        }
                    }
                }
            }

            foreach (var cue in catalog.OfChannel(CueChannel.Impact))
            {
                foreach (var layer in cue.Layers)
                {
                    if (users.TryGetValue(layer, out var set))
                    {
                        set.Add(cue.Name);
                    }
                }
            }

            foreach (var pair in EventSources())
            {
                if (users.TryGetValue(pair.Key, out var set) && !pair.Key.StartsWith("impact.", StringComparison.Ordinal))
                {
                    set.Add("event " + pair.Value);
                }
            }

            return users.ToDictionary(p => p.Key, p => p.Value.Count == 0 ? "—" : Compact(p.Value), StringComparer.Ordinal);
        }

        private static string Compact(SortedSet<string> users)
        {
            const int Shown = 6;
            return users.Count <= Shown ? string.Join(", ", users) : string.Join(", ", users.Take(Shown)) + $" +{users.Count - Shown} more";
        }

        /// <summary>Which combat events (with flags) map to each event-driven cue.</summary>
        private static Dictionary<string, string> EventSources()
        {
            var sources = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            var variants = new (CombatEventFlags Flags, int Value, string Label)[]
            {
                (CombatEventFlags.None, 0, ""),
                (CombatEventFlags.Heavy, 0, " (heavy)"),
                (CombatEventFlags.Counter, 0, " (counter)"),
                (CombatEventFlags.Finisher, 0, " (finisher)"),
                (CombatEventFlags.None, 1, " (hard)"),
            };
            foreach (CombatEventType type in Enum.GetValues(typeof(CombatEventType)))
            {
                foreach (var (flags, value, label) in variants)
                {
                    var e = new CombatEvent(1, type, 0, 1, 0, value, 0, FixedVector2.Zero, flags);
                    string cue = EventCueMap.ForEvent(e);
                    if (cue == null)
                    {
                        continue;
                    }

                    if (!sources.TryGetValue(cue, out var set))
                    {
                        set = new SortedSet<string>(StringComparer.Ordinal);
                        sources.Add(cue, set);
                    }

                    set.Add(type + label);
                }
            }

            // A plain label wins over flagged duplicates that map to the same cue.
            return sources.ToDictionary(p => p.Key, p =>
            {
                var plain = p.Value.Where(v => !v.Contains('(')).ToList();
                return string.Join(", ", plain.Count > 0 ? plain : p.Value.ToList());
            }, StringComparer.Ordinal);
        }
    }
}
