using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Oathsunder.Combat.Content;
using Oathsunder.Combat.Definitions;
using Oathsunder.Presentation.Animation;

namespace Oathsunder.Tools
{
    /// <summary>Frame data per weapon, the clip list and cue usage (Documentation/05-CoreCombat/Generated-FrameData.md).</summary>
    internal static class FrameDataReport
    {
        public static string Build(CombatContentSet content, List<(string Weapon, FighterBlueprint Blueprint, List<MoveAnimationSpec> Specs)> fighters)
        {
            var text = new StringBuilder();
            text.AppendLine("<!-- Generated by Tools/DotNet/Oathsunder.Tools.FrameData from the shipped JSON. Do not edit by hand. -->");
            text.AppendLine();
            text.AppendLine("## Frame data");
            foreach (var (weapon, blueprint, _) in fighters)
            {
                text.AppendLine();
                text.AppendLine($"### {content.MoveSet(weapon).DisplayName} (`{weapon}`) + universal techniques");
                text.AppendLine();
                text.Append(FrameDataCalculator.ToMarkdown(FrameDataCalculator.Calculate(blueprint)));
            }

            text.AppendLine();
            text.AppendLine("## Animation clip specification");
            text.AppendLine();
            text.AppendLine("Every clip is authored at 60 fps and must contain exactly the listed frame count. Key frames are 1-based move frames.");
            text.AppendLine("The simulation owns root motion, so clips are authored **in place**; the travel column is captured from the running");
            text.AppendLine("simulation and is what the character actually moves. Full per-frame curves, key poses, box timelines and cue");
            text.AppendLine("triggers are in [Production/03-Animation/Generated-AnimationLibrary.md](../Production/03-Animation/Generated-AnimationLibrary.md).");
            text.AppendLine();
            text.AppendLine("| Clip | Move | Frames | Seconds | First active | Last active | Root motion | Travel X (m) | Notes |");
            text.AppendLine("|---|---|---:|---:|---:|---:|---|---:|---|");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var (_, _, specs) in fighters)
            {
                foreach (var spec in specs)
                {
                    var move = spec.Move;
                    if (!seen.Add(spec.Clip))
                    {
                        continue;
                    }

                    string notes = move.Paired != null
                        ? $"Paired; victim clip `{move.Paired.VictimAnimation}`, release on frame {move.Paired.ReleaseFrame}"
                        : (move.HasFlag(MoveFlags.LandCancel) ? "Air; land-cancel" : "");
                    text.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "| `{0}` | {1} | {2} | {3:0.000} | {4} | {5} | {6} | {7:0.00} | {8} |",
                        spec.Clip, move.Id, move.TotalFrames, spec.Seconds,
                        move.FirstActiveFrame == 0 ? "—" : move.FirstActiveFrame.ToString(CultureInfo.InvariantCulture),
                        move.LastActiveFrame == 0 ? "—" : move.LastActiveFrame.ToString(CultureInfo.InvariantCulture),
                        spec.RootMotion, spec.FinalOffset.X.ToDouble(), notes));
                }
            }

            text.AppendLine();
            text.AppendLine("## Presentation cues");
            text.AppendLine();
            text.AppendLine("Cue names referenced by move data. Every cue is specified in the cue catalog");
            text.AppendLine("([Production/Generated-CueCatalog.md](../Production/Generated-CueCatalog.md)) and bound to assets in the `CombatCueLibrary`.");
            text.AppendLine();
            text.AppendLine("| Cue | Channel | Used by |");
            text.AppendLine("|---|---|---|");
            var cues = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            foreach (var (_, blueprint, _) in fighters)
            {
                foreach (var move in blueprint.Moves)
                {
                    foreach (var cue in move.Cues)
                    {
                        if (!cues.TryGetValue(cue.Name, out var users))
                        {
                            users = new SortedSet<string>(StringComparer.Ordinal);
                            cues.Add(cue.Name, users);
                        }

                        users.Add(move.Id);
                    }
                }
            }

            foreach (var pair in cues)
            {
                text.AppendLine($"| `{pair.Key}` | {pair.Key.Split('.')[0]} | {string.Join(", ", pair.Value)} |");
            }

            return text.ToString();
        }
    }
}
