using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Oathsunder.Combat.Content;
using Oathsunder.Combat.Definitions;

namespace Oathsunder.Tools
{
    /// <summary>
    /// Generates the data-derived parts of the combat documentation from the shipped JSON:
    /// frame data per weapon, the animation clip specification and the presentation cue list.
    /// Usage: <c>dotnet run -c Release -- [output.md]</c>.
    /// </summary>
    internal static class Program
    {
        private static int Main(string[] args)
        {
            var content = ContentLocator.Load();
            var text = new StringBuilder();
            text.AppendLine("<!-- Generated by Tools/DotNet/Oathsunder.Tools.FrameData from the shipped JSON. Do not edit by hand. -->");

            var blueprints = new List<FighterBlueprint>();
            foreach (var setId in content.MoveSetIds.OrderBy(id => id, StringComparer.Ordinal))
            {
                if (setId != "moveset.universal")
                {
                    blueprints.Add(content.BuildBlueprint("fighter.rhen", "moveset.universal", setId));
                }
            }

            text.AppendLine();
            text.AppendLine("## Frame data");
            foreach (var blueprint in blueprints)
            {
                var weapon = blueprint.MoveSetIds[blueprint.MoveSetIds.Length - 1];
                text.AppendLine();
                text.AppendLine($"### {content.MoveSet(weapon).DisplayName} (`{weapon}`) + universal techniques");
                text.AppendLine();
                text.Append(FrameDataCalculator.ToMarkdown(FrameDataCalculator.Calculate(blueprint)));
            }

            text.AppendLine();
            text.AppendLine("## Animation clip specification");
            text.AppendLine();
            text.AppendLine("Every clip is authored at 60 fps and must contain exactly the listed frame count. Key frames are 1-based move frames.");
            text.AppendLine("Root motion is extracted by the simulation from the move data, so clips are authored **in place**; the listed");
            text.AppendLine("distance is what the character travels and is provided so animators can match foot contacts.");
            text.AppendLine();
            text.AppendLine("| Clip | Move | Frames | Seconds | First active | Last active | Root motion X (m) | Notes |");
            text.AppendLine("|---|---|---:|---:|---:|---:|---:|---|");
            var seenClips = new HashSet<string>(StringComparer.Ordinal);
            foreach (var blueprint in blueprints)
            {
                foreach (var move in blueprint.Moves)
                {
                    if (string.IsNullOrEmpty(move.Animation) || !seenClips.Add(move.Animation))
                    {
                        continue;
                    }

                    string notes = move.Paired != null
                        ? $"Paired; victim clip `{move.Paired.VictimAnimation}`, release on frame {move.Paired.ReleaseFrame}"
                        : (move.HasTag(MoveTags.Air) ? "Air; land-cancel" : "");
                    text.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "| `{0}` | {1} | {2} | {3:0.000} | {4} | {5} | {6:0.00} | {7} |",
                        move.Animation, move.Id, move.TotalFrames, move.TotalFrames / 60.0,
                        move.FirstActiveFrame == 0 ? "—" : move.FirstActiveFrame.ToString(CultureInfo.InvariantCulture),
                        move.LastActiveFrame == 0 ? "—" : move.LastActiveFrame.ToString(CultureInfo.InvariantCulture),
                        RootMotion(move), notes));
                }
            }

            text.AppendLine();
            text.AppendLine("## Presentation cues");
            text.AppendLine();
            text.AppendLine("Cue names referenced by move data. Each needs an entry in the `CombatCueLibrary` asset (VFX prefab, sound, camera shake, haptics).");
            text.AppendLine();
            text.AppendLine("| Cue | Category | Used by |");
            text.AppendLine("|---|---|---|");
            var cues = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            foreach (var blueprint in blueprints)
            {
                foreach (var move in blueprint.Moves)
                {
                    foreach (var cue in move.Cues)
                    {
                        if (!cues.TryGetValue(cue.Name, out var users))
                        {
                            users = new SortedSet<string>(StringComparer.Ordinal);
                            cues.Add(cue.Name, users);
                        }

                        users.Add(move.Id);
                    }
                }
            }

            foreach (var pair in cues)
            {
                string category = pair.Key.Split('.')[0];
                text.AppendLine($"| `{pair.Key}` | {category} | {string.Join(", ", pair.Value)} |");
            }

            if (args.Length > 0)
            {
                File.WriteAllText(args[0], text.ToString());
                Console.WriteLine($"Wrote {args[0]}");
            }
            else
            {
                Console.Write(text.ToString());
            }

            return 0;
        }

        /// <summary>Horizontal distance travelled from scripted motion segments (grounded, no pushback).</summary>
        private static double RootMotion(MoveDefinition move)
        {
            double metres = 0;
            foreach (var segment in move.Motion)
            {
                if (segment.SetX)
                {
                    metres += segment.Velocity.X.ToDouble() * segment.Window.Length;
                }
            }

            return metres;
        }
    }
}
